"""Add more fields to the User Model

Revision ID: 93f5d0cd8c81
Revises: 01bf8501a352
Create Date: 2026-03-26 21:46:58.093994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f5d0cd8c81'
down_revision: Union[str, None] = '01bf8501a352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bvn_is_verified', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('users', sa.Column('cac_is_verified', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('users', sa.Column('tin_is_verified', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('users', sa.Column('address_is_verified', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address_is_verified')
    op.drop_column('users', 'tin_is_verified')
    op.drop_column('users', 'cac_is_verified')
    op.drop_column('users', 'bvn_is_verified')
    # ### end Alembic commands ###
