"""Add more fields to the User Model

Revision ID: e9d0361d072a
Revises: 0092ce910d5e
Create Date: 2026-03-25 10:38:38.500588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d0361d072a'
down_revision: Union[str, None] = '0092ce910d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('users', sa.Column('year_founded', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('business_website', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_tin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_cac_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_registration_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('business_directors', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('documents', sa.JSON(), nullable=True))
    op.alter_column('users', 'business_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'business_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'documents')
    op.drop_column('users', 'business_directors')
    op.drop_column('users', 'business_registration_date')
    op.drop_column('users', 'business_cac_number')
    op.drop_column('users', 'business_tin')
    op.drop_column('users', 'business_phone_number')
    op.drop_column('users', 'business_description')
    op.drop_column('users', 'business_address')
    op.drop_column('users', 'business_website')
    op.drop_column('users', 'employee_count')
    op.drop_column('users', 'year_founded')
    op.drop_column('users', 'industry')
    # ### end Alembic commands ###
